- name: Loops Demo
  hosts: localhost
  tasks:
    - name: Print Fruit Name
      debug:
        msg: Fruit Name - {{ item }}
      loop:
        - Apple
        - Banana
        - Orange

# for i in Apple Banana; do echo $i
